# Generated by Django 2.2 on 2019-05-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_medications'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
