# Generated by Django 2.2.1 on 2019-05-28 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_medication_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationadministration',
            name='medication_event',
        ),
        migrations.DeleteModel(
            name='MedicationEvent',
        ),
    ]
