# Generated by Django 2.2.1 on 2019-05-28 02:35

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_temperature'),
        ('health', '0003_auto_20190528_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationRecurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrence', recurrence.fields.RecurrenceField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_recurrence', to='core.Child', verbose_name='Child')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_recurrence', to='health.Medication', verbose_name='Medication')),
            ],
            options={
                'verbose_name': 'Medication recurrence',
                'verbose_name_plural': 'Medication recurrence',
                'default_permissions': ('view', 'add', 'change', 'delete'),
            },
        ),
    ]
