# Generated by Django 2.2.1 on 2019-06-02 12:33

from django.db import migrations, models
import django.utils.timezone
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_medicationrecurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationrecurrence',
            name='start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start date'),
        ),
        migrations.AddField(
            model_name='medicationrecurrence',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Alert time'),
        ),
        migrations.AlterField(
            model_name='medicationrecurrence',
            name='recurrence',
            field=recurrence.fields.RecurrenceField(verbose_name='Schedule'),
        ),
    ]
