# Generated by Django 2.2.2 on 2019-06-18 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_auto_20190618_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationadministration',
            name='recurrence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_administration', to='health.MedicationRecurrence', verbose_name='Schedule'),
        ),
    ]
